# Imports

In [22]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

# ML Evaluation/Metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score

# Loads Data

In [3]:
df = pd.read_csv(r"League_Result_Data/Encoded_PremierLeague_Stats_From_2014to2021.csv")

In [4]:
df

,Unnamed: 0,Season,Season Encoding,Date,YearOfSeason,HomeTeam,HomeTeam Encoding,AwayTeam,AwayTeam Encoding,FTHG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,0,Fall,0,12/09/2020,2020/21,Fulham,8,Arsenal,0,0.0,...,2.0,6.0,12.0,12.0,2.0,3.0,2.0,2.0,0.0,0.0
1,1,Fall,0,12/09/2020,2020/21,Crystal Palace,6,Southampton,21,1.0,...,3.0,5.0,14.0,11.0,7.0,3.0,2.0,1.0,0.0,0.0
2,2,Fall,0,12/09/2020,2020/21,Liverpool,13,Leeds,11,4.0,...,6.0,3.0,9.0,6.0,9.0,0.0,1.0,0.0,0.0,0.0
3,3,Fall,0,12/09/2020,2020/21,West Ham,28,Newcastle,17,0.0,...,3.0,2.0,13.0,7.0,8.0,7.0,2.0,2.0,0.0,0.0
4,4,Fall,0,13/09/2020,2020/21,West Brom,27,Leicester,12,0.0,...,1.0,7.0,12.0,9.0,2.0,5.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,2564,Spring,2,24/05/15,2014/15,Everton,7,Tottenham,25,0.0,...,1.0,3.0,12.0,8.0,3.0,5.0,1.0,2.0,0.0,0.0
2565,2565,Spring,2,24/05/15,2014/15,Hull,10,Man United,15,0.0,...,6.0,1.0,12.0,15.0,8.0,1.0,2.0,2.0,0.0,1.0
2566,2566,Spring,2,24/05/15,2014/15,Leicester,12,QPR,19,5.0,...,7.0,2.0,7.0,6.0,5.0,6.0,0.0,0.0,0.0,0.0
2567,2567,Spring,2,24/05/15,2014/15,Man City,14,Southampton,21,2.0,...,6.0,4.0,13.0,8.0,8.0,4.0,1.0,1.0,0.0,0.0
2568,2568,Spring,2,24/05/15,2014/15,Newcastle,17,West Ham,28,2.0,...,4.0,1.0,9.0,9.0,2.0,3.0,2.0,1.0,0.0,0.0

In [5]:
# Had this column get created upon loading, just dropped it
df = df.drop(columns=["Unnamed: 0"]) 
df

,Season,Season Encoding,Date,YearOfSeason,HomeTeam,HomeTeam Encoding,AwayTeam,AwayTeam Encoding,FTHG,FTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,Fall,0,12/09/2020,2020/21,Fulham,8,Arsenal,0,0.0,3.0,...,2.0,6.0,12.0,12.0,2.0,3.0,2.0,2.0,0.0,0.0
1,Fall,0,12/09/2020,2020/21,Crystal Palace,6,Southampton,21,1.0,0.0,...,3.0,5.0,14.0,11.0,7.0,3.0,2.0,1.0,0.0,0.0
2,Fall,0,12/09/2020,2020/21,Liverpool,13,Leeds,11,4.0,3.0,...,6.0,3.0,9.0,6.0,9.0,0.0,1.0,0.0,0.0,0.0
3,Fall,0,12/09/2020,2020/21,West Ham,28,Newcastle,17,0.0,2.0,...,3.0,2.0,13.0,7.0,8.0,7.0,2.0,2.0,0.0,0.0
4,Fall,0,13/09/2020,2020/21,West Brom,27,Leicester,12,0.0,3.0,...,1.0,7.0,12.0,9.0,2.0,5.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,Spring,2,24/05/15,2014/15,Everton,7,Tottenham,25,0.0,1.0,...,1.0,3.0,12.0,8.0,3.0,5.0,1.0,2.0,0.0,0.0
2565,Spring,2,24/05/15,2014/15,Hull,10,Man United,15,0.0,0.0,...,6.0,1.0,12.0,15.0,8.0,1.0,2.0,2.0,0.0,1.0
2566,Spring,2,24/05/15,2014/15,Leicester,12,QPR,19,5.0,1.0,...,7.0,2.0,7.0,6.0,5.0,6.0,0.0,0.0,0.0,0.0
2567,Spring,2,24/05/15,2014/15,Man City,14,Southampton,21,2.0,0.0,...,6.0,4.0,13.0,8.0,8.0,4.0,1.0,1.0,0.0,0.0
2568,Spring,2,24/05/15,2014/15,Newcastle,17,West Ham,28,2.0,0.0,...,4.0,1.0,9.0,9.0,2.0,3.0,2.0,1.0,0.0,0.0

# Split the Data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2569 entries, 0 to 2568
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Season                 2569 non-null   object
 1   Season Encoding        2569 non-null   int64
 2   Date                   2569 non-null   object
 3   YearOfSeason           2414 non-null   object
 4   HomeTeam               2569 non-null   object
 5   HomeTeam Encoding      2569 non-null   int64
 6   AwayTeam               2569 non-null   object
 7   AwayTeam Encoding      2569 non-null   int64
 8   FTHG                   2569 non-null   float64
 9   FTAG                   2569 non-null   float64
 10  FTR                    2569 non-null   object
 11  FTR Encoding           2569 non-null   int64
 12  HTHG                   2569 non-null   float64
 13  HTAG                   2569 non-null   float64
 14  HTR                    2569 non-null   object
 15  HTR Encoding           2569 non-null   int64
 16  Referee                2569 non-null   object
 17  Referee Encoding       2569 non-null   int64
 18  Fouls Called Per Game  2569 non-null   float64
 19  HS                     2569 non-null   float64
 20  AS                     2569 non-null   float64
 21  HST                    2569 non-null   float64
 22  AST                    2569 non-null   float64
 23  HF                     2569 non-null   float64
 24  AF                     2569 non-null   float64
 25  HC                     2569 non-null   float64
 26  AC                     2569 non-null   float64
 27  HY                     2569 non-null   float64
 28  AY                     2569 non-null   float64
 29  HR                     2569 non-null   float64
 30  AR                     2569 non-null   float64
dtypes: float64(17), int64(6), object(8)
memory usage: 622.3+ KB

In [7]:
# Features -- Drops FTR and any categorical value 
X = df.drop(columns=["Season", "YearOfSeason", "Date", "FTHG","FTAG", "HTHG","HTAG" ,"HomeTeam", "AwayTeam", "Referee", "FTR", "FTR Encoding", "HTR", "Referee"])
# Labels
y = df["FTR Encoding"]

In [8]:
X

,Season Encoding,HomeTeam Encoding,AwayTeam Encoding,HTR Encoding,Referee Encoding,Fouls Called Per Game,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,0,8,0,1,7,14.0,5.0,13.0,2.0,6.0,12.0,12.0,2.0,3.0,2.0,2.0,0.0,0.0
1,0,6,21,0,27,14.0,5.0,9.0,3.0,5.0,14.0,11.0,7.0,3.0,2.0,1.0,0.0,0.0
2,0,13,11,0,28,14.0,22.0,6.0,6.0,3.0,9.0,6.0,9.0,0.0,1.0,0.0,0.0,0.0
3,0,28,17,2,11,13.0,15.0,15.0,3.0,2.0,13.0,7.0,8.0,7.0,2.0,2.0,0.0,0.0
4,0,27,12,2,10,15.0,7.0,13.0,1.0,7.0,12.0,9.0,2.0,5.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2564,2,7,25,1,27,14.0,9.0,16.0,1.0,3.0,12.0,8.0,3.0,5.0,1.0,2.0,0.0,0.0
2565,2,10,15,2,15,13.0,16.0,7.0,6.0,1.0,12.0,15.0,8.0,1.0,2.0,2.0,0.0,1.0
2566,2,12,19,0,28,14.0,22.0,18.0,7.0,2.0,7.0,6.0,5.0,6.0,0.0,0.0,0.0,0.0
2567,2,14,21,0,2,14.0,15.0,13.0,6.0,4.0,13.0,8.0,8.0,4.0,1.0,1.0,0.0,0.0
2568,2,17,28,2,16,14.0,17.0,4.0,4.0,1.0,9.0,9.0,2.0,3.0,2.0,1.0,0.0,0.0

In [9]:
y

0       1
1       0
2       0
3       1
4       1
       ..
2564    1
2565    2
2566    0
2567    0
2568    0
Name: FTR Encoding, Length: 2569, dtype: int64

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Scale Features

In [25]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Logistic Regression

In [89]:
log_clf = LogisticRegression(random_state=42, penalty='l1', solver='saga', 
                             multi_class='ovr',tol=1e-3)
log_clf = log_clf.fit(X_train, y_train)

score = log_clf.score(X_test, y_test)

print(score)

0.6167315175097277

In [90]:
# Confusion Matrix

cv_score = cross_val_score(log_clf, X_train, y_train, cv=3, scoring='accuracy')

print(cv_score, '\n')

y_train_pred = cross_val_predict(log_clf, X_train, y_train, cv=3)
print(confusion_matrix(y_train, y_train_pred))

[0.6189781  0.62189781 0.60875912]

[[730 121  68]
 [154 447  48]
 [219 178  90]]